name: CI - Run Tests

on:
  push:
    branches:
      - main
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Debug GitHub Context
        run: |
          echo "Event Name: ${{ github.event_name }}"
          echo "Branch ref: ${{ github.ref }}"
          echo "Branch name: ${{ github.ref_name }}"
          echo "Head ref: ${{ github.head_ref }}"
          echo "Base ref: ${{ github.base_ref }}"

      - name: Set BASE_URL
        run: echo "BASE_URL=${{ github.base_ref == 'dev--' && 'dev' || '' }}" >> $GITHUB_ENV

      - name: Create .env file
        run: |
          touch .env
          echo BASE_API_URL=${{ secrets.BASE_API_URL }} >> .env
          echo DATABASE_NAME=${{ secrets.DATABASE_NAME }} >> .env
          echo DATABASE_VERSION=${{ secrets.DATABASE_VERSION }} >> .env
          echo DATABASE_OBJECT_STORE_NAME=${{ secrets.DATABASE_OBJECT_STORE_NAME }} >> .env

      - name: Verify .env File
        run: cat .env

      - name: Log BASE_URL
        run: echo "BASE_URL=$BASE_URL"

      - name: Run Jest tests
        run: npm test

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        env:
          BASE_URL: 'https://${{ env.BASE_URL }}cooknify.netlify.app'
        run: npx playwright test

      - name: Upload Playwright Trace
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
