name: Deploy Preview & Testing for PR

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Debug GitHub Context
        run: |
          echo "Event Name: ${{ github.event_name }}"
          echo "Branch ref: ${{ github.ref }}"
          echo "Branch name: ${{ github.ref_name }}"
          echo "Head ref: ${{ github.head_ref }}"
          echo "Base ref: ${{ github.base_ref }}"

      # Untuk push (bukan PR), gunakan URL statis sesuai branch
      - name: Set BASE_URL dynamically for push events
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/dev" || "${{ github.base_ref }}" == "dev" ]]; then
            echo "BASE_URL=https://dev-cooknify.netlify.app" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/main" || "${{ github.base_ref }}" == "main" ]]; then
            echo "BASE_URL=https://cooknify.netlify.app" >> $GITHUB_ENV
          fi

      - name: Log BASE_URL
        run: echo "BASE_URL=$BASE_URL"

      - name: Create .env file
        run: |
          touch .env
          echo BASE_API_URL=${{ secrets.BASE_API_URL }} >> .env
          echo DATABASE_NAME=${{ secrets.DATABASE_NAME }} >> .env
          echo DATABASE_VERSION=${{ secrets.DATABASE_VERSION }} >> .env
          echo DATABASE_OBJECT_STORE_NAME=${{ secrets.DATABASE_OBJECT_STORE_NAME }} >> .env

      - name: Verify .env File
        run: cat .env

      - name: Build Project
        if: ${{ !env.BASE_URL }}
        run: npm run build

      - name: Run Jest tests
        run: npm test

      - name: Clear Playwright Cache
        run: rm -rf ~/.cache/ms-playwright

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        env:
          BASE_URL: ${{ env.BASE_URL }}
        run: npx playwright test

      - name: Upload Playwright Trace
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-trace
          path: test-results/
          retention-days: 30
