jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    outputs:
      deploy-url: ${{ steps.netlify.outputs.deploy-url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Create .env file
        run: |
          touch .env
          echo "BASE_API_URL=${{ secrets.BASE_API_URL }}" >> .env
          echo "DATABASE_NAME=${{ secrets.DATABASE_NAME }}" >> .env
          echo "DATABASE_VERSION=${{ secrets.DATABASE_VERSION }}" >> .env
          echo "DATABASE_OBJECT_STORE_NAME=${{ secrets.DATABASE_OBJECT_STORE_NAME }}" >> .env
          echo "BASE_URL=https://localhost" >> .env

      - name: Verify .env before build
        run: cat .env

      - name: Build Project
        run: npm run build

      - name: Deploy to Netlify (PR Preview)
        id: netlify
        uses: nwtgck/actions-netlify@v3.0
        with:
          publish-dir: './dist'
          deploy-message: 'Preview for PR #${{ github.event.pull_request.number }}'
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

      - name: Debug Netlify Output
        env:
          DEPLOY_URL: ${{ steps.netlify.outputs.deploy-url }}
        run: echo "Deploy URL from Netlify=$DEPLOY_URL"

      - name: Post Comment with Preview Link
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: 'PR Preview deployed: ${{ steps.netlify.outputs.deploy-url }}'

  testing:
    runs-on: ubuntu-latest
    needs: deploy-preview
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Set BASE_URL from Deploy Preview
        run: echo "BASE_URL=$DEPLOY_URL" >> $GITHUB_ENV
        env:
          DEPLOY_URL: ${{ needs.deploy-preview.outputs.deploy-url }}

      - name: Verify BASE_URL
        run: echo "BASE_URL from Deploy Preview=$BASE_URL"

      - name: Create .env file
        run: |
          touch .env
          echo "BASE_API_URL=${{ secrets.BASE_API_URL }}" >> .env
          echo "DATABASE_NAME=${{ secrets.DATABASE_NAME }}" >> .env
          echo "DATABASE_VERSION=${{ secrets.DATABASE_VERSION }}" >> .env
          echo "DATABASE_OBJECT_STORE_NAME=${{ secrets.DATABASE_OBJECT_STORE_NAME }}" >> .env
          echo "BASE_URL=$BASE_URL" >> .env

      - name: Verify .env File
        run: cat .env

      - name: Run Jest tests
        run: npm test

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        env:
          BASE_URL: ${{ env.BASE_URL }}
        run: npx playwright test

      - name: Upload Playwright Trace
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-trace
          path: test-results/
          retention-days: 30
