# Name of workflow
name: Production workflow

# When workflow is triggered
on:
  push:
    tags:
      - 'v*'

# Jobs to carry out
jobs:
  deploy:
    timeout-minutes: 60
    # Operating system to run job on
    runs-on: ubuntu-latest

    # Steps in job
    steps:
      # Get code from repo
      - name: Checkout repository
        uses: actions/checkout@v4
      # Install NodeJS
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      # Install Dependencies
      - name: Install dependencies
        run: npm ci
      # Create environment variables
      - name: Create .env file
        run: |
          touch .env
          echo BASE_URL=${{ secrets.BASE_URL }} >> .env
          echo BASE_API_URL=${{ secrets.BASE_API_URL }} >> .env
          echo DATABASE_NAME=${{ secrets.DATABASE_NAME }} >> .env
          echo DATABASE_VERSION=${{ secrets.DATABASE_VERSION }} >> .env
          echo DATABASE_OBJECT_STORE_NAME=${{ secrets.DATABASE_OBJECT_STORE_NAME }} >> .env
      # Run Build
      - name: Build
        run: npm run build
      # Deploy to Netlify using our dev secrets
      - name: Deploy to netlify
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        with:
          args: deploy --dir=build --prod
          secrets: '["NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID"]'
