name: Testing

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Debug GitHub Context
        run: |
          echo "Branch ref: ${{ github.ref }}"
          echo "Branch name: ${{ github.ref_name }}"
          echo "Head ref: ${{ github.head_ref }}"
          echo "Base ref: ${{ github.base_ref }}"

      - name: Set BASE_URL dynamically
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/dev" || "${{ github.base_ref }}" == "dev" ]]; then
            echo "BASE_URL=https://dev-cooknify.netlify.app" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/main" || "${{ github.base_ref }}" == "main" ]]; then
            echo "BASE_URL=https://cooknify.netlify.app" >> $GITHUB_ENV
          fi

      - name: Log BASE_URL
        run: echo "BASE_URL=$BASE_URL"

      - name: Install dependencies
        run: npm ci

      - name: Create .env file
        run: |
          touch .env
          echo BASE_API_URL=${{ secrets.BASE_API_URL }} >> .env
          echo DATABASE_NAME=${{ secrets.DATABASE_NAME }} >> .env
          echo DATABASE_VERSION=${{ secrets.DATABASE_VERSION }} >> .env
          echo DATABASE_OBJECT_STORE_NAME=${{ secrets.DATABASE_OBJECT_STORE_NAME }} >> .env

      - name: Verify .env File
        run: cat .env

      - name: Run Jest tests
        run: npm test

      - name: Clear Playwright Cache
        run: rm -rf ~/.cache/ms-playwright

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        env:
          BASE_URL: ${{ env.BASE_URL }}
        run: npx playwright test

      - name: Upload Playwright Report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
